// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwsCareer.Database.Sqlite;

#nullable disable

namespace Swos.CareerMod.Database.Sqlite.Migrations
{
    [DbContext(typeof(SqliteCareerModDbContext))]
    [Migration("20240109201845_AddTeamsAndCoaches")]
    partial class AddTeamsAndCoaches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Swos.CareerMod.Database.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Tactic")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("Swos.CareerMod.Database.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusRating")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Face")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("YouthRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Swos.CareerMod.Database.Models.PlayerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrimarySkill")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Skill")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SkillValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerSkills");
                });

            modelBuilder.Entity("Swos.CareerMod.Database.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayKitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeKitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AwayKitId");

                    b.HasIndex("CoachId");

                    b.HasIndex("HomeKitId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Swos.CareerMod.Database.Models.TeamKit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("KitType")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ShirtExtraColor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ShirtMainColor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ShortsColor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SocksColor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TeamKits");
                });

            modelBuilder.Entity("Swos.CareerMod.Database.Models.Player", b =>
                {
                    b.HasOne("Swos.CareerMod.Database.Models.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Swos.CareerMod.Database.Models.PlayerSkill", b =>
                {
                    b.HasOne("Swos.CareerMod.Database.Models.Player", null)
                        .WithMany("Skills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Swos.CareerMod.Database.Models.Team", b =>
                {
                    b.HasOne("Swos.CareerMod.Database.Models.TeamKit", "AwayKit")
                        .WithMany()
                        .HasForeignKey("AwayKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swos.CareerMod.Database.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swos.CareerMod.Database.Models.TeamKit", "HomeKit")
                        .WithMany()
                        .HasForeignKey("HomeKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayKit");

                    b.Navigation("Coach");

                    b.Navigation("HomeKit");
                });

            modelBuilder.Entity("Swos.CareerMod.Database.Models.Player", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Swos.CareerMod.Database.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
